[package]
name = "geo-shit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
geo = "0.26.0"
geo-types = "0.7.11"
s2 = "0.0.12"
wkt = "0.10.3"
